### ISSUE TITLE
Prior distribution for Savage Dickey Density Ratio (BF) of an estimated difference

### ISSUE THREAD

**Issue by HusseinJouni** [easystats/bayestestR#244]
Hello :)

I am a bayestestR user for computing Bayes Factor on estimated difference between products thanks to a Bayesian mixed model using Rstanarm. 
The function that i use is bayesfactor_parameters.

It is explained in the R documentation that, for an object if class 'emmGrid', we have to put the stanreg model as the "prior" argument.

My question is : how the prior distribution is computed for the calculation of the BF thanks to the savage dickey ratio ?
I know that it is sampled, but it's still unclear for me.

Many thanks !

**Comment by mattansb** [comment]
Hi @HusseinJouni !

In any `rstanarm` modeling function, you can request for the function to sample from the prior distribution (based on the `prior` specification or default) instead of from the posterior distribution, by setting `prior_PD = TRUE`. For example:
```r
fit <- stan_lmer(extra ~ group + (1 | ID),
                 data = sleep,
                 prior_PD = TRUE)
```

Behind the scenes, `bayesfactor_parameter` simply runs `update(mode, prior_PD = TRUE)`, and let's `rstanarm` do all the heavy lifting to produce the samples from the prior distribution (a similar scheme is used form `brms`).

Hope that answers your question!

**Comment by mattansb** [comment]
Excellent question - never trust the magic we do here in `easystats` if you can't see the strings!

**Comment by HusseinJouni** [comment]
Many thanks you have answered :)
