### ISSUE TITLE
Error with brmsfit objects passed to `equivalence_test()`

### ISSUE THREAD

**Issue by JCruk** [easystats/bayestestR#293]
I am working on summarizing some results of a binomial (bernoulli) model fitted with BRMS and when passing the model to `equivalence_test()` I get the following error:

Error in `[.data.frame`(as.data.frame(model), , valid_parameters) : 
  undefined columns selected

When I run as.data.frame(model) a data frame of all parameters is returned.

I've also tried specifying a single parameter and receive the same error.
```
equivalence_test(How_BRMS_Nested_Mod,
                 parameters = "b_ConditionIntervention")
```

It's a hierarchical model with nested random effects.

**Comment by strengejacke** [comment]
brms changed the behaviour of `as.data.frame()` recently, and we have already fixed this... Can you please update [insight](https://github.com/easystats/insight/) from GitHub and check if your issue is solved? If not, please try updating bayestestR from GitHub as well.

If all these measures don't work, we have to see if we can build a reproducible example...

**Comment by JCruk** [comment]
Installing bayestestR from github did the trick (I was already using the github version of insight).

Thank you for this package and the entire collection of amazing tools you provide and maintain!

**Comment by strengejacke** [comment]
@DominiqueMakowski @mattansb bayestestR is now for more than 6 weeks on CRAN, I think we should submit an update, because this is a rather "critical" issue, or not?

**Comment by mattansb** [comment]
Agreed.

**Comment by DominiqueMakowski** [comment]
Will submit asap
