### ISSUE TITLE
Bayes vignette

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#33]
Would you say that it makes sense to "copy" this vignette from sjstats:
https://strengejacke.github.io/sjstats/articles/bayesian-statistics.html

Or maybe revise it slightly?

**Comment by DominiqueMakowski** [comment]
This might be related to a more general question pertaining to BayestestR's documentation 😏 

One way of doing it could be:
- Having extensive *function-specific* documentation as function docstrings, which could include links to the vignettes.
- The vignettes would would be of different nature:
  - **Indices presentation**: These vignettes would present and discuss the indices (currently for instance, there is one for point estimates and one for indices of effect existence).
  - **Methods justification**: These vignettes would discuss some caveats and parameters, e.g., what is the difference between different types of HDI, how is the rope range computed, why these defaults etc.
  - **Hands on examples**: These vignettes would show how to use bayestestR to conduct Bayesian analyses.

Since we have a package devoted to Bayesian stuff, it might be worth trying presenting the documentation in a more segregated way, rather than having all information on one? What do you think?

Nevertheless, if you agree on that, we could definitely use what you've already written, and maybe split it into different parts :)

**Comment by strengejacke** [comment]
Sounds good!

**Comment by strengejacke** [comment]
What exactly is a "function docstrings"? The related help-file?

**Comment by DominiqueMakowski** [comment]
Yes ^^, the docs written in the roxygen section above the function, which is automatically formatted into help-files (it's called docstrings in python and others, I thought it was a generic name 😄)

**Comment by DominiqueMakowski** [comment]
I think currently the vignette meets the minimum requirement for now. But I plan a heavy improvement from a didactic perspective once things like plotting, performance, and report are available. Hopefully for v2

**Comment by DominiqueMakowski** [comment]
Closing this for #38
