### ISSUE TITLE
ETI / CI still fails at printing

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#354]
``` r
bayestestR::eti(iris$Sepal.Length)
#> # Equal-Tailed Interval
#> Error in names(df) <- col_names: 'names' attribute [1] must be the same length as the vector [0]
```

<sup>Created on 2020-12-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Was reported by a user, despite latest update

**Comment by DominiqueMakowski** [comment]
Probably still due the new printing, but should it be fixed in insight or here? @strengejacke

**Comment by mattansb** [comment]
Have you updated insight following #353?

**Comment by strengejacke** [comment]
Yes, is resolved in current GitHub insight. @DominiqueMakowski maybe you can add some tests with `capture.output()` to validate the print? Not sure why this was not caught on CRAN, afaik the example are not wrapped into `\dontrun{}`.

**Comment by mattansb** [comment]
Can use [`expect_output(print(x), "something")`](https://testthat.r-lib.org/reference/expect_output.html).
E.g., https://github.com/easystats/effectsize/blob/master/tests/testthat/test-printing.R

Also, maybe we can start adding remotes in the description file, so that when installing GitHub versions, it also installs the latest dependencies? (Then those lines can be removed before sending to CRAN).

**Comment by strengejacke** [comment]
> Also, maybe we can start adding remotes in the description file, 

Yes, I do this as well, when necessary.
