### ISSUE TITLE
allow more objects

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#5]
I think it would be nice to have methods for stanfit or brms-objects as well, so the functions not only expect a single vector, but may also cope with model objects.

**Comment by DominiqueMakowski** [comment]
Yes, although I am not sure about its place in this package... I am still wondering whether it wouldn't be easier to have one package devoted solely to the pure processing of posterior vectors, and then one mid-level package, devoted to "models parameters metrics computation", that could use this package in order to compute the relevant metrics for Bayesian models (as well as, for instance, p values for frequentist models).
