### ISSUE TITLE
ROPE and predictor scaling

### ISSUE THREAD

**Issue by rvlenth** [easystats/bayestestR#559]
**Describe the bug**
I received a request to add ROPE analysis to my **emmeans** package; and specifically, the person requesting this pointed to the function `bayestestR::rope()` applied to a model. Before I consider it, I need to understand what it is. So I did some testing...

**To Reproduce**
The first example for `rope(model)`:
```
> library(rstanarm)
> model <- stan_glm(mpg ~ wt + gear, data = mtcars, chains = 2, iter = 200, refresh = 0)

> library(bayestestR)
> rope(model)
# Proportion of samples inside the ROPE [-0.60, 0.60]:

Parameter   | inside ROPE
-------------------------
(Intercept) |      0.00 %
wt          |      0.00 %
gear        |     56.32 %
```
Now I tried it after changing weight in 1000 lbs to weight in lbs. 
```
> mtcars$wtlbs = 1000*mtcars$wt
> model.lbs <- stan_glm(mpg ~ wtlbs + gear, data = mtcars, chains = 2, iter = 200, refresh = 0)
> rope(model.lbs)
# Proportion of samples inside the ROPE [-0.60, 0.60]:

Parameter   | inside ROPE
-------------------------
(Intercept) |      0.00 %
wtlbs       |    100.00 %
gear        |     44.21 %
```
The two models are the same except for scale. But the ROPE percent changed from 0 to 100! Why? Because we are using the same default range of (-.6, +.6) while the posterior values for `wt` are about 1000 times those for `wtlbs`. 

But *neither* makes sense! Regression coefficients are *slopes*. The units for the one for `wt` are mpg per 1000 lbs, and the units for `wtlbs`'s coefficient is mpg per lb. Meanwhile, the units for the range are just in mpg. 

By the way, yes, I could use `range` to specify intervals to achieve comparable results. But that doesn't cut the mustard either because that range is used for *all* the predictors, and each coefficient needs its *own* range. 

**Expected behaviour**
I would expect ROPE results for model coefficients to be invariant to scaling of the predictors.

I am afraid that if this type of analysis has been used a lot for model coefficients, there are a lot of seriously misleading results out there. Sorry to be bringing you this message; but in the long run, you'll be sorrier than me if it weren't fixed.

**Specifications (please complete the following information):**
 - bayestestR version 0.12.1

**Comment by DominiqueMakowski** [comment]
Hi Russell, thanks for chiming in!

I believe this is related to [this section](https://easystats.github.io/bayestestR/articles/region_of_practical_equivalence.html#sensitivity-to-parameters-scale) of the documentation and [this section](https://easystats.github.io/bayestestR/reference/rope.html#sensitivity-to-parameter-s-scale) of the docstrings.

Sensitivity to scale is a critical characteristic of ROPE indeed, and is not a bug of our implementation. In general ROPE-based indices require a lot of thought and understanding (even simply to specify meaningful ROPE bounds) - and thus is not appropriate for automated & mindless usage. We tried to make it as clear as possible by discussing it throughout our documentation, and I can only hope users read it... 

As to why we have it in bayestestR at all, 1) it can be a very useful index to test specific hypotheses regarding effect size and 2) bayestestR aims at implementing a wide range of indices - including some that are unperfect (which is actually all of them). We then make a more opinionated selection of indices used by default in other packages built on bayestestR, such as [`parameters`](https://github.com/easystats/parameters) and [`report`](https://github.com/easystats/report). 

Hope that clarifies!

**Comment by bwiernik** [comment]
- [ ] To add, you can think of the implementation of ROPE as assuming  that each predictor has been scaled so that a one unit change is a meaningful difference. There really isn't a reasonable universal default way to scale all predictor variables. Eg, thinking about standardized variables, depending on the variable, a 1 SD change might be an implausibly large amount (eg, levels of program funding, atmospheric particulate concentration), a trivial amount (eg, age in a relatively homogeneous sample), or a nonsensical unit (eg, a group index variable). For a useful discussion of this issue, see https://www.tandfonline.com/doi/pdf/10.1207/S15327906MBR3403_2?casa_token=QD9-zte1aDwAAAAA:pfdiYXbU8uwI-DgtpHEOVnhSSFHXYuuSNelXaUZrTOuV_4yzpxFSH8QjZia9lJoHLHFMxVo5CK-P

There really isn't any way for ROPE to be useful as a statistic without some thought as to what degrees of change on a predictor are practically useful. To that end, variables are best scaled appropriately prior to modeling. For example, if fully standardized variables are useful for you, you could standardize the predictors using `datawizard::standardize()` prior to modeling.

**Comment by bwiernik** [comment]
We could consider adding an argument to post-hoc rescale predictor variables for ROPE analysis, something like `rope_predictor_scale`. That would be difficult to handle for things like polynomial terms or other transformations, but those sorts of models should probably be examined using predicted values and contrasts rather than parameters directly

**Comment by rvlenth** [comment]
I agree that careful thought is important. I just don't see evidence of careful thought in the examples for `rope()`. And I think putting things on a Cohen's *d* scale encourages people to *not* think carefully, because the units are gone.

And since you mention it, to me it is clearly *not* sensible to apply the same ROPE range for each coefficient in a polynomial term, no matter how that variable is scaled.

**Comment by strengejacke** [comment]
According to your example, I would say that:

For model 1, when a car's weight increases by 1000lbs, we find a meaningful change in our outcome. For model 2,  when a car's weight increases by 1 lbs, this doesn't seem to have any relevant impact on our outcome.

I don't think each parameter needs its own rope-range - this would "only" make rope _values_ comparable across parameters, but still you need to know more details about the scales to make meaningful conclusions.

Thus, I'd say that the rope "works as intended", it's just that interpretation is "hard" (and requires caution and thinking).

**Comment by strengejacke** [comment]
> to me it is clearly not sensible to apply the same ROPE range for each coefficient in a polynomial term

True, but this is almost the same when you try to interpret the coefficients. For such cases, I'd rather use predictions.
