### ISSUE TITLE
docs map_estimate

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#58]
@DominiqueMakowski [This commit](https://github.com/easystats/bayestestR/commit/aa2c197679f46e4882a2307aec7e859e1b632fe3) requires some attention! Since `map_estimate()` returns different things, depending on the input and the arguments, I tried to add the section for the return-value to the docs. However, I'm not sure what `density` does. so can you check this please, and add a short description to the `@return`-part of the docs?

**Comment by DominiqueMakowski** [comment]
Thanks for pointing that out! You're right, I think this is a bad design choice. Better to stick with the return in the form of a dataframe containing the two values. Also, I've added more info about them. Will be in upcoming PR

**Comment by DominiqueMakowski** [comment]
After thinking a bit more I've decided to re-set the inclusion of the density value to optional as I think most users won't expect nor need it. I tried to document it better in the documentation.

**Comment by DominiqueMakowski** [comment]
I am still hesitating with this one... currently MAP_estimate always returns a dataframe with one or two column). However, users might expect a single value instead of a dataframe. The density value of the MAP (the possible second column) was initially added because it is used in `p_map` and because it *might* be worth something (#59). At the same time, it can be easily retrieved using `density_at`, although it is computationally not very efficient (i.e. the density function would be estimated twice). 

Nevertheless, maybe it's better to harmonize it with other functions and return a single value (in case a single posterior is passed) instead of always a dataframe...

**Comment by strengejacke** [comment]
Well, you still have attributes (to save the density value), and you can add a `print()`-method. What is printed (many information) and what is returned for further computation (a numeric value, with attrbiute) can be something different.

**Comment by DominiqueMakowski** [comment]
storing the density value as an attribute solves all problems. Thanks for that :)

**Comment by DominiqueMakowski** [comment]
Well I am kind of disappointed to find out that numeric cannot really take attributes... 😅  More precisely, adding attributes to a numeric make the tests fail. If I create a new class `c("MAP", "numeric"), the tests also fail... See #67 

Returning a list seems a bit as going back to the dataframe behaviour 😕

**Comment by strengejacke** [comment]
You can actually check for values with attributes in tests, I have done this somewhere in on of my / our packages... I must check if I can find it...

**Comment by DominiqueMakowski** [comment]
I think this has been addressed
