### ISSUE TITLE
rope/equivalence test

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#6]
@strengejacke I am still unsure about the name of the equivalence test, currently called [rope_test()](https://easystats.github.io/bayestestR/reference/rope_test.html) (as it is directly related to the `rope()` function. I know that you named it equi_test in sjstats (although to be used on models instead of vectors of posteriors). What is your opinion?

**Comment by strengejacke** [comment]
The wording is based on Kruschke's paper (https://journals.sagepub.com/doi/10.1177/2515245918771304). You mainly test a parameter for equivalence, so he called it "equivalence testing", and that's why I chose a name that should reflect this somehow.

I think the difference is that _rope_ just defines a region of values, but does not actually _test_ for equivalence. You don't test the _region_ (the rope), but you test your parameters, if they're practically equivalent to "zero effect".

**Comment by DominiqueMakowski** [comment]
Makes sense indeed. I shall rename it `equivalence_test()` then 😊 (If you don't mind of course!)

**Comment by DominiqueMakowski** [comment]
Sure, what other functions would you have in mind?

**Comment by strengejacke** [comment]
I'm primarily thinking about these functions:
https://strengejacke.github.io/sjstats/reference/hdi.html

However, they could (should?) work with Stan-models out-of-the-box.

**Comment by strengejacke** [comment]
https://strengejacke.github.io/sjstats/reference/tidy_stan.html could maybe be something for reporter?!?

**Comment by DominiqueMakowski** [comment]
> I'm primarily thinking about these functions:
> https://strengejacke.github.io/sjstats/reference/hdi.html

This ties down to the design pickle of #7

> https://strengejacke.github.io/sjstats/reference/tidy_stan.html could maybe be something for reporter?!?

Yes, or the "parameters" brick 😏
