### ISSUE TITLE
Scope of the package

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/bayestestR#7]
Related to #5 #6 

Currently, all functions in the package are "model agnostic", i.e., they don't work on models but directly on the posterior vectors. 

These are fundamental operations that would be used in functions dealing with Bayesian models.

In fact, I first considered dissociating the "model-related" part with the "posterior-related" part, but writing about this, I am not sure it makes much sense. First, the scope (and name) of the package suggests its ability to deal with models. And second, it would nice to have the same function names for posteriors and models (`hdi(rnorm(1000))` and `hdi(stanmodel)`).

The other possibility would be to move the model-targetted functions to the "parameters" (such as sjstats::tidy_stan) and "model performance" (e..g. for sjstats::msce) packages.

What is your feeling about this?

**Comment by strengejacke** [comment]
I think it's difficult to separate. In the end, each object returned by rstanarm or brms is nothing else but a "collection of posterior vectors" (in the form of a data frame, when you call `as.data.frame()`). Most operations you do on a Stan-model-object are operations on the posterior draws from that model.

I'm not sure if it's necessary to separate out the extraction of posterior draws into a separate package. From the perspective of my workflow, I would fit a model and try to get statistics like HDI, MCSE, ROPE, MAP/median "point estimate" etc. directly from that model.

I would also say it's more comfortable for the end-user to have just one package when working with Bayesian models, instead of loading two (or more) packages, one that can be used with the model-objects directly and another one for posterior distributions as vector. You can, of course, have a high-level packages with two different packages underlying it, where the high-level package returns the statistics, and internally either calls the package for the vector-stuff or model-stuff, but then we build up an internal dependency-bulge that could be avoided.

I think we can do some brainstorming about the functions that should go into this package, and then maybe we have a clearer view that helps us deciding whether we should dissociate model- from posterior-part. If the overlap of functions is small, we can go for two separate packages?

**Comment by DominiqueMakowski** [comment]
I guess you're right. For all the functions currently implemented, its adaptation to support models should be quite straightforward (we should just have a `get_posteriors()` function (in `insight`?), extract them, and run the functions). If I'm not mistaken, the main thing to "add", really, would be the functions related to the chains/model convergence.

However, I have the feeling that this package should remain relatively raw, made to compute the relevant things, without focusing too much on presentation (pretty printing and display), leaving the formatting of the indices to other packages (such as performance, parameters and report).
