### ISSUE TITLE
Inconsistency with plot(equivalence_test(model))

### ISSUE THREAD

**Issue by drchriscole** [easystats/bayestestR#78]
This looks like a great project. Will follow it with great interest.

In your [blog](https://easystats.github.io/blog/posts/bayestestr_presentation/) post the plot() function labels the decisions on whether to reject H0 differently (opposite?) to the equivalence_test() output. e.g. 'wt' is accepted in the plot, but rejected by the test. This doesn't seem right or am I missing something?

**Comment by strengejacke** [comment]
Both outputs are correct, because they refer to different aspects:

- `print.equivalence_test()` indicates whether _H0_ is rejected or accepted
- `plot.equivalence_test()`, however, indicates whether _a parameter_ is rejected or accepted

If _H0_ is _rejected, the _parameter_ is _accepted.

@DominiqueMakowski Should we address this, and if yes, how? Describe it in the docs, or should we add a "decision" column to the `print()`-method, or change the `H0`-column with a `decision`-column?

**Comment by DominiqueMakowski** [comment]
We should definitely unify the 2 outputs. Maybe swap the `plot` method "reject" and "accept" names, and add change the legend title accordingly, for instance "decision about H0"?

**Comment by drchriscole** [comment]
ah, thanks for the expalanation. The difference is confusing without additional wording.
